# please refer to the datura documentation for a full list of configurable settings
# any custom settings you create here will be accessible in instances of classes
# like FileTei and TeiToEs ( @options["setting_name"] )
# you may also create new environments

# please put any sensitive information or computer specific settings in private.yml!

default:
  collection: whitman-LG_1855_variorum
  data_base: https://servername.unl.edu/media  # (do not include /data/ in path)
  media_base: https://servername.unl.edu/media

  # iiif settings
  iiif_base: https://servername.unl.edu/iiif/2
  # only applies to TEI, for snippets alter CSV
  iiif_fig_dir: "published%2FLG%2Ffigures%2F"
  iiif_fullsize_end: "full/full/0/default.jpg"
  iiif_thumb_end: "full/!150,150/0/default.jpg"

  tei_html_xsl: scripts/overrides/LG55_variorum.xsl
  variables_html:
    siteroot: https://whitmanarchive.org/
    externalfileroot: http://whitmanarchive.org/
    nbPathRoot: ../../../whitman-notebooks/source/tei/
    msPathRoot: ../../../whitman-manuscripts/source/tei/
    margPathRoot: ../../../whitman-marginalia/source/tei/
    variorumPathRoot: ../../source/authority/
    nbPathHTMLRoot: ../../../item/
    msPathHTMLRoot: ../../../item/
    margAnnoPathHTMLRoot: ../../../item/
    margPathHTMLRoot: ../../../item/
    variorumPathHTMLRoot: ../../../item/
  api_version: "2.0"
  es_index: whitman-api_v2
  threads: 5

development:
  data_base: https://servername.unl.edu/media  # (do not include /data/ in path)
  variables_html:
    siteroot: https://servername.unl.edu/
  es_index: whitman-api_v2

# production:
  # limit processed files by adding allowed ids on newlines in a file
  # allowed_files: config/allowed.txt
