# please refer to the datura documentation for a full list of configurable settings
# any custom settings you create here will be accessible in instances of classes
# like FileTei and TeiToEs ( @options["setting_name"] )
# you may also create new environments

# please put any sensitive information or computer specific settings in private.yml!

default:
  collection: whitman-LG_1855_variorum
  data_base: https://whitmanarchive.org/media  # (do not include /data/ in path)
  media_base: https://whitmanarchive.org/media

  # iiif settings
  iiif_base: https://whitmanarchive.org/iiif/2
  # only applies to TEI, for snippets alter CSV
  iiif_fig_dir: "published%2FLG%2Ffigures%2F"
  iiif_fullsize_end: "full/full/0/default.jpg"
  iiif_thumb_end: "full/!150,150/0/default.jpg"

  tei_html_xsl: scripts/overrides/LG55_variorum.xsl
  variables_html:
    siteroot: https://whitmanarchive.org/
    externalfileroot: http://whitmanarchive.org/
    nbPathRoot: /var/local/www/collections/whitman-notebooks/source/tei/
    msPathRoot: /var/local/www/collections/whitman-manuscripts/source/tei/
    margPathRoot: /var/local/www/collections/whitman-marginalia/source/tei/
    variorumPathRoot: /var/local/www/collections/whitman-LG_1855_variorum/source/authority/
    nbPathHTMLRoot: /var/local/www/collections/whitman-notebooks/output/production/html/
    msPathHTMLRoot: /var/local/www/collections/whitman-manuscripts/output/production/html/
    margAnnoPathHTMLRoot: /var/local/www/collections/whitman-marginalia/output/production/html/
    margPathHTMLRoot: /var/local/www/collections/whitman-marginalia/output/production/html/
    variorumPathHTMLRoot: /var/local/www/collections/whitman-LG_1855_variorum/output/production/html/

development:
  data_base: https://whitman-dev.unl.edu/media  # (do not include /data/ in path)
  variables_html:
    siteroot: https://whitman-dev.unl.edu/
    externalfileroot: http://whitmanarchive.org/
    nbPathRoot: /var/local/www/data/collections/whitman-notebooks/source/tei/
    msPathRoot: /var/local/www/data/collections/whitman-manuscripts/source/tei/
    margPathRoot: /var/local/www/data/collections/whitman-marginalia/source/tei/
    variorumPathRoot: /var/local/www/data/collections/whitman-LG_1855_variorum/source/authority/
    nbPathHTMLRoot: /var/local/www/data/collections/whitman-notebooks/output/development/html/
    msPathHTMLRoot: /var/local/www/data/collections/whitman-manuscripts/output/development/html/
    margAnnoPathHTMLRoot: /var/local/www/data/collections/whitman-marginalia/output/development/html/
    margPathHTMLRoot: /var/local/www/data/collections/whitman-marginalia/output/development/html/
    variorumPathHTMLRoot: /var/local/www/data/collections/whitman-LG_1855_variorum/output/development/html/

# production:
  # limit processed files by adding allowed ids on newlines in a file
  # allowed_files: config/allowed.txt
