# please refer to the datura documentation for a full list of configurable settings
# any custom settings you create here will be accessible in instances of classes
# like FileTei and TeiToEs ( @options["setting_name"] )
# you may also create new environments

# please put any sensitive information or computer specific settings in private.yml!

default:
  # please fill in the name of your collection here
  # collection:
  collection: whitman-variorum
  data_base: https://whitmanarchive.org/media  # (do not include /data/ in path)
  media_base: https://whitmanarchive.org/media

  # refer to the documentation for details about overriding the XSL
  # html_html_xsl:
  tei_html_xsl: scripts/overrides/LG55_variorum.xsl
  # vra_html_xsl:
  variables_html:
    siteroot: https://whitman-dev.unl.edu/
    externalfileroot: http://whitmanarchive.org/
    nbPathRoot: /var/local/www/cocoon/whitmanarchive/manuscripts/notebooks/tei/
    msPathRoot: /var/local/www/cocoon/whitmanarchive/manuscripts/tei/
    variorumPathRoot: /var/local/www/data/collections/whitman-variorum/source/authority/
    nbPathHTMLRoot: manuscripts/notebooks/transcriptions/
    msPathHTMLRoot: manuscripts/transcriptions/
    variorumPathHTMLRoot: published/LG/1855/related/

development:
  data_base: https://whitman-dev.unl.edu/media  # (do not include /data/ in path)

  # es_index: cdrhapidev-v1
  # es_path: https://cdrhdev1.unl.edu/elastic

# production:
  # limit processed files by adding allowed ids on newlines in a file
  # allowed_files: config/allowed.txt
