# please refer to the datura documentation for a full list of configurable settings
# any custom settings you create here will be accessible in instances of classes
# like FileTei and TeiToEs ( @options["setting_name"] )
# you may also create new environments

# please put any sensitive information or computer specific settings in private.yml!

default:
  collection: whitman-variorum
  data_base: https://whitmanarchive.org/media  # (do not include /data/ in path)
  media_base: https://whitmanarchive.org/media

  # iiif settings
  iiif_base: https://whitmanarchive.org/iiif/2
  # only applies to TEI, for snippets alter CSV
  iiif_fig_dir: "published%2FLG%2Ffigures%2F"
  iiif_fullsize_end: "full/full/0/default.jpg"
  iiif_thumb_end: "full/!150,150/0/default.jpg"

  tei_html_xsl: scripts/overrides/LG55_variorum.xsl
  variables_html:
    siteroot: https://whitmanarchive.org/
    externalfileroot: http://whitmanarchive.org/
    nbPathRoot: /var/local/www/cocoon/whitmanarchive/manuscripts/notebooks/tei/
    msPathRoot: /var/local/www/cocoon/whitmanarchive/manuscripts/tei/
    margPathRoot: /var/local/www/cocoon/whitmanarchive/manuscripts/marginalia/tei/
    variorumPathRoot: /var/local/www/data/collections/whitman-variorum/source/authority/
    nbPathHTMLRoot: manuscripts/notebooks/transcriptions/
    msPathHTMLRoot: manuscripts/transcriptions/
    margPathHTMLRoot: manuscripts/marginalia/transcriptions/
    variorumPathHTMLRoot: published/LG/1855/related/

development:
  data_base: https://whitman-dev.unl.edu/media  # (do not include /data/ in path)
  variables_html:
    siteroot: https://whitman-dev.unl.edu/
    externalfileroot: http://whitmanarchive.org/
    nbPathRoot: /var/local/www/cocoon/whitmanarchive/manuscripts/notebooks/tei/
    msPathRoot: /var/local/www/cocoon/whitmanarchive/manuscripts/tei/
    margPathRoot: /var/local/www/cocoon/whitmanarchive/manuscripts/marginalia/tei/
    variorumPathRoot: /var/local/www/data/collections/whitman-variorum/source/authority/
    nbPathHTMLRoot: manuscripts/notebooks/transcriptions/
    msPathHTMLRoot: manuscripts/transcriptions/
    margPathHTMLRoot: manuscripts/marginalia/transcriptions/
    variorumPathHTMLRoot: published/LG/1855/related/

# production:
  # limit processed files by adding allowed ids on newlines in a file
  # allowed_files: config/allowed.txt
